# Generated by Django 6.0.4 on 2026-05-03 00:59

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.MyUserManager()),
            ],
        ),
    ]
